import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
// import { GeistMono } from "geist/font/mono";
import "./globals.css";

const morpheus = localFont({
    src: [
        {
            path: "../public/fonts/Morpheus.ttf",
            weight: "500",
            style: "normal",
        },
    ],
    variable: "--font-morpheus",
});

export const metadata: Metadata = {
    title: "AishUI World of warcraft",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="fr" suppressHydrationWarning>
                <head>
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <meta charSet="utf-8" />
                </head>
                <body className={`${GeistSans.className} ${morpheus.variable}`}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}
